version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: microblog
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Manila
    restart: unless-stopped
    volumes: [db:/var/lib/mysql]

  web:
    build:
      args:
        PHP_MODE: production
      context: .
    depends_on: [db]
    restart: unless-stopped
    volumes: [./:/var/www/html]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "5000:80"

volumes:
  db: